### ISSUE TITLE
HTML rendering does not like CSS variables

### ISSUE THREAD

**Issue by jrymk** [duoani/obsidian-habit-tracker#8]
Here's my CSS snippet:
```css
.hlinv {
    --bgcol: var(--yellow);
    /* default color */
    color: white;
    background-image: linear-gradient(360deg, rgba(255, 255, 255, 0) 0%, var(--bgcol) 5%, var(--bgcol) 95%, rgba(255, 255, 255, 0) 100%) !important;
    padding-left: 0.2em;
    padding-right: 0.2em;
}
```

And 
````md
```habitt
[month:2023-02]
(19, Test)
(20, <span class="hlinv">Test</span>)
(21, <span class="hlinv" style="--bgcol: var(--purple)">Test</span>)
(22, <span class="hlinv" style="color: #FF0000">Test</span>)

```

Test
<span class="hlinv">Test</span>
<span class="hlinv" style="--bgcol: var(--purple)">Test</span>
````
renders as 
![image](https://user-images.githubusercontent.com/39593345/219898778-b7fe1edb-94e1-45e1-8e13-55c2bce32ff1.png)

If any CSS custom properties (--something) is used, the whole thing is not rendered out.
Do you have any idea of why this is happening?
